/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-lowest': '#ffffff',
        'surface': '#fbf8fc',
        'surface-dim': '#dbd9dd',
        'surface-container-low': '#f5f3f7',
        'surface-container': '#efedf1',
        'surface-container-high': '#e9e7eb',
        'on-surface': '#1b1b1e',
        'on-surface-variant': '#444937',
        primary: '#4d6700',
        'on-primary': '#ffffff',
        'primary-container': '#d4ff70',
        'on-primary-container': '#587600',
        'primary-fixed': '#c7f264',
        'on-primary-fixed-variant': '#394d00',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        tertiary: '#5c47cd',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#f2edff',
        'on-tertiary-container': '#6b57dc',
        'tertiary-fixed': '#e5deff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#747965',
        'outline-variant': '#c4c9b2',
        'inverse-surface': '#303033',
        'inverse-on-surface': '#f2f0f4',
        'inverse-primary': '#acd54b',
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
